<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>Assets\mwc_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="C:\Users\winba\.nuget\packages\windowsinput\6.4.1\contentFiles\any\net6.0-windows7.0\.nuget\mouse-keyboard-hook-logo.png" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\frame00.png" />
    <None Remove="Assets\frame01.png" />
    <None Remove="Assets\frame02.png" />
    <None Remove="Assets\frame03.png" />
    <None Remove="Assets\frame04.png" />
    <None Remove="Assets\frame05.png" />
    <None Remove="Assets\frame06.png" />
    <None Remove="Assets\frame07.png" />
    <None Remove="Assets\frame08.png" />
    <None Remove="Assets\frame09.png" />
    <None Remove="Assets\frame10.png" />
    <None Remove="Assets\frame11.png" />
    <None Remove="Assets\TrayFrames\frame00.ico" />
    <None Remove="Assets\TrayFrames\frame01.ico" />
    <None Remove="Assets\TrayFrames\frame02.ico" />
    <None Remove="Assets\TrayFrames\frame03.ico" />
    <None Remove="Assets\TrayFrames\frame04.ico" />
    <None Remove="Assets\TrayFrames\frame05.ico" />
    <None Remove="Assets\TrayFrames\frame06.ico" />
    <None Remove="Assets\TrayFrames\frame07.ico" />
    <None Remove="Assets\TrayFrames\frame08.ico" />
    <None Remove="Assets\TrayFrames\frame09.ico" />
    <None Remove="Assets\TrayFrames\frame10.ico" />
    <None Remove="Assets\TrayFrames\frame11.ico" />
    <None Remove="mwc_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="NetFwTypeLib">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>58fbcf7c-e7a9-467c-80b3-fc65e8fcca08</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="{215d64d2-031c-33c7-96e3-61794cd1ee61}">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>4</VersionMinor>
      <VersionMajor>2</VersionMajor>
      <Guid>215d64d2-031c-33c7-96e3-61794cd1ee61</Guid>
    </COMReference>
    <COMReference Include="IWshRuntimeLibrary">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>f935dc20-1cf0-11d0-adb9-00c04fd58a0b</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.Wpf.TaskbarNotification" Version="1.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Octokit" Version="14.0.0" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="9.0.6" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.6" />
    <PackageReference Include="TaskScheduler" Version="2.12.1" />
    <PackageReference Include="WindowsInput" Version="6.4.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\mwc_icon.ico" />
    <Resource Include="Assets\TrayFrames\frame00.ico" />
    <Resource Include="Assets\TrayFrames\frame01.ico" />
    <Resource Include="Assets\TrayFrames\frame02.ico" />
    <Resource Include="Assets\TrayFrames\frame03.ico" />
    <Resource Include="Assets\TrayFrames\frame04.ico" />
    <Resource Include="Assets\TrayFrames\frame05.ico" />
    <Resource Include="Assets\TrayFrames\frame06.ico" />
    <Resource Include="Assets\TrayFrames\frame07.ico" />
    <Resource Include="Assets\TrayFrames\frame08.ico" />
    <Resource Include="Assets\TrayFrames\frame09.ico" />
    <Resource Include="Assets\TrayFrames\frame10.ico" />
    <Resource Include="Assets\TrayFrames\frame11.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
